### PR TITLE
faq.ejs: Links to more information (MSE + Discord)

### PR DESCRIPTION
**Pull request by tripleee**
Add a FAQ section with links to further information

### CODE REVIEW

**Comment by tripleee** [comment]
The link in the footer of the site (which I did not spot while looking for the Discord link) is different from the one I have in the PR; I don't know what the difference between them is, but the one I use here seems to be the canonical one in some sense. Should the footer use the same link, or should the PR be updated to use the one from the footer (or doesn't it matter really)?

**Comment by ws909** [comment]
The Discord invitation link in the footer has expired. Either a permanent link should be acquired, or one which can be manually retracted; or we should get automatic updates of it, or schedule manual replacements.

**Comment by ws909** [comment]
[Link to a non-expiring invitation here](https://discord.com/channels/628507458452586497/628509392987226122/765992275519340554): https://discord.gg/PbEPURd

**Comment by tripleee** [comment]
See also now #51

**Pull request merged**
